const border = [
  { x: 0, y: 0, w: 360, h: 18 },
  { x: 0, y: 0, w: 18, h: 640 },
  { x: 342, y: 0, w: 18, h: 640 },
  { x: 0, y: 622, w: 360, h: 18 },
];

const levelList = [
  {
    id: 'rabbit-fall',
    order: 1,
    chapter: '第一章',
    eyebrow: 'I · 追逐白影',
    name: '兔子洞没有底',
    mechanic: '倾斜与惯性',
    parTime: 35000,
    hint: '顺着白兔留下的脚印，学习控制速度',
    quote: '她追着一只迟到的白影，掉进了一个没有方向的地方。',
    story: [
      {
        speaker: '白兔',
        portrait: 'rabbit',
        text: '迟了，迟了！公爵夫人的钟可不会等一个迷路的小姑娘。',
      },
      {
        speaker: '爱丽丝',
        portrait: 'alice',
        text: '它会说话，还穿着背心。既然洞已经把我吞下去，我总得看看它通向哪里。',
      },
    ],
    start: { x: 55, y: 568 },
    goal: { x: 284, y: 38, w: 42, h: 52 },
    next: ['hall-of-doors'],
    items: [{ id: 'cameo-rabbit-fall', type: 'curiosity', x: 302, y: 560, r: 11 }],
    walls: [
      ...border,
      { x: 18, y: 506, w: 220, h: 18 },
      { x: 112, y: 410, w: 230, h: 18 },
      { x: 18, y: 314, w: 220, h: 18 },
      { x: 112, y: 218, w: 230, h: 18 },
      { x: 18, y: 122, w: 220, h: 18 },
    ],
  },
  {
    id: 'hall-of-doors',
    order: 2,
    chapter: '第二章',
    eyebrow: 'II · 金色门厅',
    name: '所有门都太小',
    mechanic: '钥匙与机关门',
    parTime: 50000,
    hint: '先取钥匙，再踩亮玫瑰印章',
    lockedHint: '锁孔轻声说：还缺一件事情。',
    quote: '钥匙能打开门，却不能替她决定该走向哪里。',
    story: [
      {
        speaker: '旁白',
        portrait: 'key',
        text: '长桌上放着一把小金钥匙。它能打开最矮的门，可爱丽丝还是太大了。',
      },
      {
        speaker: '爱丽丝',
        portrait: 'alice',
        text: '先找到钥匙，再问门肯不肯讲道理。这里的顺序似乎比大小更重要。',
      },
    ],
    eventStories: {
      'collect:gold-key': {
        speaker: '爱丽丝',
        portrait: 'alice',
        text: '正是那把金钥匙。现在只差让玫瑰印章承认我来过。',
      },
    },
    start: { x: 53, y: 570 },
    goal: {
      x: 286,
      y: 38,
      w: 40,
      h: 52,
      requires: { items: ['gold-key'], switches: ['rose-seal'] },
    },
    next: ['pool-of-tears'],
    items: [
      { id: 'gold-key', type: 'key', x: 292, y: 548, r: 12 },
      { id: 'cameo-hall', type: 'curiosity', x: 302, y: 262, r: 11 },
    ],
    switches: [{ id: 'rose-seal', x: 58, y: 174, r: 18 }],
    gates: [{ id: 'rose-gate', switchId: 'rose-seal', x: 150, y: 112, w: 34, h: 112 }],
    walls: [
      ...border,
      { x: 18, y: 494, w: 250, h: 18 },
      { x: 91, y: 398, w: 251, h: 18 },
      { x: 18, y: 302, w: 250, h: 18 },
      { x: 91, y: 206, w: 59, h: 18 },
      { x: 184, y: 206, w: 158, h: 18 },
      { x: 18, y: 112, w: 132, h: 18 },
      { x: 184, y: 112, w: 90, h: 18 },
    ],
  },
  {
    id: 'pool-of-tears',
    order: 3,
    chapter: '第三章',
    eyebrow: 'III · 泪水之池',
    name: '眼泪会记得方向',
    mechanic: '水流与危险区',
    parTime: 60000,
    hint: '水流会推着你走，避开深蓝色漩涡',
    quote: '她哭出一片海，随后不得不学会在自己的眼泪里游泳。',
    story: [
      {
        speaker: '爱丽丝',
        portrait: 'alice',
        text: '我一会儿变大，一会儿变小，连眼泪都积成了池塘。哭完以后，路还是得自己找。',
      },
      {
        speaker: '渡渡鸟的声音',
        portrait: 'rabbit',
        text: '大家都湿透了。至于谁赢了比赛，当然是每个人都赢了。',
      },
    ],
    start: { x: 52, y: 568 },
    goal: { x: 282, y: 38, w: 44, h: 52 },
    next: ['caterpillar-crossroad'],
    items: [{ id: 'cameo-pool', type: 'curiosity', x: 140, y: 470, r: 11 }],
    zones: [
      { type: 'current', x: 32, y: 438, w: 296, h: 72, forceX: 0.85, forceY: 0 },
      { type: 'current', x: 32, y: 245, w: 296, h: 72, forceX: -0.8, forceY: -0.12 },
      { type: 'ice', x: 36, y: 104, w: 286, h: 92 },
    ],
    hazards: [
      { id: 'tear-whirlpool-1', type: 'whirlpool', x: 286, y: 474, r: 19 },
      { id: 'tear-whirlpool-2', type: 'whirlpool', x: 73, y: 281, r: 19 },
      { id: 'tear-whirlpool-3', type: 'whirlpool', x: 180, y: 151, r: 18 },
    ],
    walls: [
      ...border,
      { x: 18, y: 526, w: 104, h: 18 },
      { x: 174, y: 526, w: 168, h: 18 },
      { x: 18, y: 397, w: 182, h: 18 },
      { x: 250, y: 397, w: 92, h: 18 },
      { x: 18, y: 204, w: 98, h: 18 },
      { x: 168, y: 204, w: 174, h: 18 },
    ],
  },
  {
    id: 'caterpillar-crossroad',
    order: 4,
    chapter: '第四章',
    eyebrow: 'IV · 蓝烟岔路',
    name: '你是谁？',
    mechanic: '雾镜与双印章',
    parTime: 70000,
    hint: '雾镜会扰乱光影，但方向仍由你掌握；点亮两枚问号印章',
    quote: '毛毛虫只问了三个字：“你是谁？” 她却没有答案。',
    story: [
      {
        speaker: '毛毛虫',
        portrait: 'caterpillar',
        text: '你，是，谁？',
      },
      {
        speaker: '爱丽丝',
        portrait: 'alice',
        text: '今天早晨我还知道。可变了这么多次以后，我不敢说自己还是同一个人。',
      },
      {
        speaker: '毛毛虫',
        portrait: 'caterpillar',
        text: '蘑菇的一边使你长高，另一边使你变矮。至于哪一边是哪一边，你自己试。',
      },
    ],
    start: { x: 180, y: 570 },
    goal: {
      x: 159,
      y: 38,
      w: 42,
      h: 54,
      requires: { switches: ['who-left', 'who-right'] },
    },
    choices: [
      {
        id: 'mushroom',
        next: 'mushroom-forest',
        title: '吃下蘑菇',
        description: '改变自己的大小，穿过森林。',
      },
      {
        id: 'tea',
        next: 'mad-tea-party',
        title: '追随钟声',
        description: '去参加一场永远不会结束的茶会。',
      },
    ],
    items: [{ id: 'cameo-crossroad', type: 'curiosity', x: 180, y: 396, r: 11 }],
    zones: [{ type: 'mirror', x: 86, y: 190, w: 188, h: 260 }],
    switches: [
      { id: 'who-left', x: 55, y: 128, r: 18 },
      { id: 'who-right', x: 305, y: 128, r: 18 },
    ],
    gates: [{ id: 'question-gate', switchId: 'who-left', switchIds: ['who-left', 'who-right'], x: 142, y: 94, w: 76, h: 16 }],
    walls: [
      ...border,
      { x: 18, y: 512, w: 112, h: 18 },
      { x: 230, y: 512, w: 112, h: 18 },
      { x: 78, y: 438, w: 204, h: 18 },
      { x: 18, y: 352, w: 112, h: 18 },
      { x: 230, y: 352, w: 112, h: 18 },
      { x: 78, y: 266, w: 204, h: 18 },
      { x: 18, y: 180, w: 112, h: 18 },
      { x: 230, y: 180, w: 112, h: 18 },
    ],
  },
  {
    id: 'mushroom-forest',
    order: 5,
    branch: 'mushroom',
    branchLabel: '蘑菇支线',
    chapter: '第五章 A',
    eyebrow: 'V-A · 蘑菇森林',
    name: '一口太大，一口太小',
    mechanic: '体型切换与窄路',
    parTime: 75000,
    hint: '蓝药水使你变小，饼干使你变大',
    quote: '身体改变了尺寸，问题却没有因此变小。',
    story: [
      {
        speaker: '毛毛虫',
        portrait: 'caterpillar',
        text: '尺寸不是答案，只是一种通行证。小路偏爱小人，沉重的蘑菇盖却只听大人的。',
      },
      {
        speaker: '爱丽丝',
        portrait: 'alice',
        text: '那么我就保留两种自己，需要哪一种时再决定。',
      },
    ],
    start: { x: 55, y: 568 },
    goal: {
      x: 284,
      y: 38,
      w: 42,
      h: 52,
      requires: { switches: ['heavy-cap'] },
    },
    next: ['queen-garden'],
    items: [
      { id: 'blue-potion', type: 'potion', x: 286, y: 548, r: 13 },
      { id: 'cake', type: 'cookie', x: 62, y: 155, r: 13 },
      { id: 'cameo-mushroom', type: 'curiosity', x: 309, y: 448, r: 11 },
    ],
    decorations: [
      { type: 'mushroom', x: 190, y: 442, size: 72, alpha: 0.58 },
      { type: 'mushroom', x: 250, y: 248, size: 62, alpha: 0.5, flip: true },
      { type: 'mushroom', x: 122, y: 72, size: 54, alpha: 0.46 },
    ],
    switches: [{ id: 'heavy-cap', x: 290, y: 155, r: 20, minRadius: 16 }],
    walls: [
      ...border,
      { x: 18, y: 486, w: 279, h: 18 },
      { x: 321, y: 486, w: 21, h: 18 },
      { x: 72, y: 390, w: 270, h: 18 },
      { x: 18, y: 294, w: 279, h: 18 },
      { x: 321, y: 294, w: 21, h: 18 },
      { x: 72, y: 198, w: 270, h: 18 },
      { x: 18, y: 102, w: 266, h: 18 },
    ],
  },
  {
    id: 'mad-tea-party',
    order: 5,
    branch: 'tea',
    branchLabel: '茶会支线',
    chapter: '第五章 B',
    eyebrow: 'V-B · 疯茶会',
    name: '时间卡在六点',
    mechanic: '传送与旋转茶桌',
    parTime: 75000,
    hint: '踩下回转曲柄，让茶桌改成通往门的方向',
    quote: '他们不断换座位，因为时间拒绝再向前走。',
    story: [
      {
        speaker: '帽匠',
        portrait: 'hatter',
        text: '这里永远是六点。时间和我吵了一架，从此不肯再走。',
      },
      {
        speaker: '三月兔',
        portrait: 'rabbit',
        text: '没位置了！没位置了！虽然桌边明明空着一大圈。',
      },
      {
        speaker: '爱丽丝',
        portrait: 'alice',
        text: '如果他们只会换座位，我就把整张桌子转到正确的方向。',
      },
    ],
    start: { x: 52, y: 568 },
    goal: {
      x: 284,
      y: 38,
      w: 42,
      h: 52,
      requires: { items: ['watch-hand'], rotations: { 'tea-table': 1 } },
    },
    next: ['queen-garden'],
    items: [
      { id: 'watch-hand', type: 'key', x: 60, y: 116, r: 12 },
      { id: 'cameo-tea', type: 'curiosity', x: 286, y: 456, r: 11 },
    ],
    decorations: [
      { type: 'watch', x: 180, y: 350, size: 84, alpha: 0.18 },
      { type: 'watch', x: 286, y: 152, size: 48, alpha: 0.2 },
    ],
    movers: [
      {
        id: 'minute-hand',
        type: 'watch',
        path: 'orbit',
        centerX: 180,
        centerY: 350,
        radiusX: 112,
        radiusY: 42,
        w: 25,
        h: 25,
        speed: 0.0015,
      },
    ],
    switches: [
      {
        id: 'tea-crank',
        action: 'rotate',
        target: 'tea-table',
        symbol: '↻',
        x: 292,
        y: 350,
        r: 18,
      },
    ],
    rotators: [
      {
        id: 'tea-table',
        centerX: 180,
        centerY: 350,
        states: 2,
        art: 'tea-table',
        artSize: 112,
        walls: [{ x: 172, y: 343, w: 80, h: 14 }],
      },
    ],
    portals: [
      { id: 'cup-a1', pairId: 'cup-a2', color: '#9f6c66', x: 286, y: 538, r: 17 },
      { id: 'cup-a2', pairId: 'cup-a1', color: '#9f6c66', x: 75, y: 358, r: 17 },
      { id: 'cup-b1', pairId: 'cup-b2', color: '#6c9b9c', x: 290, y: 260, r: 17 },
      { id: 'cup-b2', pairId: 'cup-b1', color: '#6c9b9c', x: 75, y: 122, r: 17 },
    ],
    zones: [
      { type: 'ice', x: 105, y: 420, w: 220, h: 72 },
      { type: 'ice', x: 35, y: 178, w: 220, h: 72 },
    ],
    walls: [
      ...border,
      { x: 18, y: 508, w: 220, h: 18 },
      { x: 122, y: 402, w: 220, h: 18 },
      { x: 18, y: 296, w: 220, h: 18 },
      { x: 122, y: 190, w: 220, h: 18 },
      { x: 18, y: 84, w: 220, h: 18 },
    ],
  },
  {
    id: 'queen-garden',
    order: 6,
    chapter: '第六章',
    eyebrow: 'VI · 红心花园',
    name: '把白玫瑰涂成红色',
    mechanic: '玫瑰染色与纸牌巡逻',
    parTime: 90000,
    hint: '提起油漆桶，把三朵白玫瑰染红；第二朵会保存位置',
    quote: '规则走来走去，喊着要砍掉所有不合规则的东西。',
    story: [
      {
        speaker: '纸牌园丁',
        portrait: 'card',
        text: '我们错种了白玫瑰。女王只要红色，看见以前必须把它们涂好。',
      },
      {
        speaker: '红心女王',
        portrait: 'queen',
        text: '谁准花园里出现错误？先判决，再找证据！',
      },
      {
        speaker: '爱丽丝',
        portrait: 'alice',
        text: '她的规则只是她的脾气。可在找到出口以前，我得先穿过这些纸牌。',
      },
    ],
    eventStories: {
      'paint:queen-rose-2': {
        speaker: '纸牌园丁',
        portrait: 'card',
        text: '中间这朵记住了你的位置。女王若把你赶走，花园会偷偷送你回来。',
      },
    },
    start: { x: 52, y: 570 },
    goal: {
      x: 283,
      y: 38,
      w: 43,
      h: 52,
      requires: {
        items: ['red-paint'],
        painted: ['queen-rose-1', 'queen-rose-2', 'queen-rose-3'],
      },
    },
    choices: [
      {
        id: 'mirror',
        next: 'looking-glass',
        title: '穿过镜子',
        description: '去一条会在黑白之间改写自己的路。',
      },
      {
        id: 'croquet',
        next: 'queen-croquet',
        title: '接受女王的比赛',
        description: '规则不公平，但火烈鸟似乎更不听话。',
      },
    ],
    items: [
      { id: 'red-paint', type: 'paint', x: 58, y: 548, r: 13 },
      { id: 'cameo-queen', type: 'curiosity', x: 180, y: 452, r: 11 },
    ],
    paintables: [
      { id: 'queen-rose-1', x: 286, y: 548, r: 14 },
      { id: 'queen-rose-2', x: 180, y: 310, r: 14, checkpoint: true },
      { id: 'queen-rose-3', x: 60, y: 108, r: 14 },
    ],
    movers: [
      { id: 'card-1', type: 'card', x: 50, y: 455, w: 54, h: 16, axis: 'x', range: 220, speed: 0.0015 },
      { id: 'card-2', type: 'card', x: 250, y: 342, w: 54, h: 16, axis: 'x', range: -200, speed: 0.0019, phase: 1.2 },
      { id: 'card-3', type: 'card', x: 50, y: 226, w: 54, h: 16, axis: 'x', range: 220, speed: 0.0022, phase: 2.4 },
      { id: 'card-4', type: 'card', x: 250, y: 112, w: 54, h: 16, axis: 'x', range: -200, speed: 0.0025, phase: 0.5 },
    ],
    walls: [
      ...border,
      { x: 18, y: 514, w: 116, h: 18 },
      { x: 226, y: 514, w: 116, h: 18 },
      { x: 108, y: 397, w: 144, h: 18 },
      { x: 18, y: 282, w: 116, h: 18 },
      { x: 226, y: 282, w: 116, h: 18 },
      { x: 108, y: 166, w: 144, h: 18 },
    ],
  },
  {
    id: 'looking-glass',
    order: 7,
    branch: 'mirror',
    branchLabel: '镜中支线',
    chapter: '第七章 A',
    eyebrow: 'VII-A · 镜中走廊',
    name: '门在你的倒影身后',
    mechanic: '黑白棋路与状态钥匙',
    parTime: 105000,
    hint: '棋子会切换黑白道路；两枚碎片只在各自颜色的世界中现身',
    quote: '她向前走了两步，却看见自己从另一边靠近。',
    story: [
      {
        speaker: '镜中的红后',
        portrait: 'queen',
        text: '在这里，你必须拼命奔跑，才能留在原地。若想到别处，还得跑得更快。',
      },
      {
        speaker: '爱丽丝',
        portrait: 'alice',
        text: '棋盘每醒来一次，路就换一种颜色。我要按它的回合前进，而不是只看眼前。',
      },
    ],
    start: { x: 54, y: 570 },
    goal: {
      x: 283,
      y: 38,
      w: 43,
      h: 52,
      requires: {
        items: ['black-glass-shard', 'white-glass-shard'],
        phases: { 'mirror-chess': 1 },
      },
    },
    next: ['trial-of-names'],
    phaseRoute: [
      { target: 'glass-white-pawn', phase: 0 },
      { target: 'glass-queen', phase: 1 },
      { target: 'black-glass-shard', phase: 0 },
      { target: 'glass-black-pawn', phase: 0 },
      { target: 'white-glass-shard', phase: 1 },
      { target: 'goal', phase: 1 },
    ],
    items: [
      {
        id: 'black-glass-shard',
        type: 'key',
        x: 296,
        y: 254,
        r: 12,
        requiresPhases: { 'mirror-chess': 0 },
      },
      {
        id: 'white-glass-shard',
        type: 'key',
        x: 294,
        y: 132,
        r: 12,
        requiresPhases: { 'mirror-chess': 1 },
      },
      { id: 'mirror-checkpoint', type: 'checkpoint', x: 180, y: 360, r: 12 },
      { id: 'cameo-mirror', type: 'curiosity', x: 296, y: 458, r: 11 },
    ],
    zones: [
      { type: 'mirror', x: 34, y: 326, w: 292, h: 176 },
      { type: 'current', x: 34, y: 128, w: 292, h: 82, forceX: 0, forceY: 0.7 },
    ],
    phases: [
      {
        id: 'mirror-chess',
        initial: 0,
        wallsByState: [
          [
            { x: 240, y: 512, w: 102, h: 18 },
            { x: 240, y: 92, w: 102, h: 18 },
          ],
          [
            { x: 240, y: 308, w: 102, h: 18 },
          ],
        ],
      },
    ],
    switches: [
      {
        id: 'glass-white-pawn',
        action: 'phase',
        target: 'mirror-chess',
        phaseTo: 1,
        requiresPhase: 0,
        glyph: '♙',
        x: 300,
        y: 560,
        r: 18,
      },
      {
        id: 'glass-queen',
        action: 'phase',
        target: 'mirror-chess',
        phaseTo: 0,
        requiresPhase: 1,
        glyph: '♛',
        x: 60,
        y: 360,
        r: 18,
      },
      {
        id: 'glass-black-pawn',
        action: 'phase',
        target: 'mirror-chess',
        phaseTo: 1,
        requiresPhase: 0,
        glyph: '♟',
        x: 60,
        y: 150,
        r: 18,
      },
    ],
    hazards: [{ id: 'mirror-hole', type: 'whirlpool', x: 180, y: 169, r: 19 }],
    walls: [
      ...border,
      { x: 18, y: 512, w: 222, h: 18 },
      { x: 120, y: 410, w: 222, h: 18 },
      { x: 18, y: 308, w: 222, h: 18 },
      { x: 120, y: 206, w: 222, h: 18 },
      { x: 18, y: 92, w: 222, h: 18 },
    ],
  },
  {
    id: 'queen-croquet',
    order: 7,
    branch: 'croquet',
    branchLabel: '槌球支线',
    chapter: '第七章 B',
    eyebrow: 'VII-B · 女王的槌球场',
    name: '球门总在临时改口',
    mechanic: '火烈鸟弹射与顺序球门',
    parTime: 105000,
    hint: '撞醒发光的火烈鸟，让它把你击进同号球门；得分会开启下一赛道',
    quote: '女王说规则很简单：只要她赢，规则就永远正确。',
    story: [
      {
        speaker: '红心女王',
        portrait: 'queen',
        text: '槌球的规则很简单：火烈鸟是球槌，刺猬是球，纸牌士兵弯腰充当球门。然后由我获胜。',
      },
      {
        speaker: '火烈鸟',
        portrait: 'flamingo',
        text: '嘎。我们偶尔会把头转开，因为没有谁问过我们想不想当球槌。',
      },
      {
        speaker: '爱丽丝',
        portrait: 'alice',
        text: '那就合作一次。每只火烈鸟负责一道同号球门，得分以后下一只才会醒来。',
      },
    ],
    eventStories: {
      'bumper:flamingo-1': {
        speaker: '火烈鸟一号',
        portrait: 'flamingo',
        text: '第一杆！穿过金色虚线尽头的一号门。',
      },
      'switch:croquet-hoop-1': {
        speaker: '纸牌裁判',
        portrait: 'card',
        text: '一号球门得分。下层闸门开启，二号火烈鸟醒了。',
      },
      'switch:croquet-hoop-2': {
        speaker: '红心女王',
        portrait: 'queen',
        text: '谁允许你连续得分？把纸牌巡逻再加快一点！',
      },
      'switch:croquet-hoop-3': {
        speaker: '火烈鸟',
        portrait: 'flamingo',
        text: '三道球门都承认了这次击球。现在轮到女王遵守自己的规则。',
      },
    },
    start: { x: 52, y: 570 },
    goal: {
      x: 283,
      y: 38,
      w: 43,
      h: 52,
      requires: { switches: ['croquet-hoop-1', 'croquet-hoop-2', 'croquet-hoop-3'] },
    },
    next: ['trial-of-names'],
    items: [
      { id: 'croquet-checkpoint', type: 'checkpoint', x: 58, y: 420, r: 12 },
      { id: 'cameo-croquet', type: 'curiosity', x: 52, y: 72, r: 11 },
    ],
    switchSequence: ['croquet-hoop-1', 'croquet-hoop-2', 'croquet-hoop-3'],
    switches: [
      {
        id: 'croquet-hoop-1',
        action: 'hoop',
        order: 1,
        requiresBumper: 'flamingo-1',
        orientation: 'vertical',
        direction: 1,
        aperture: 17,
        x: 292,
        y: 520,
        r: 20,
      },
      {
        id: 'croquet-hoop-2',
        action: 'hoop',
        order: 2,
        requiresBumper: 'flamingo-2',
        orientation: 'vertical',
        direction: -1,
        aperture: 17,
        x: 66,
        y: 326,
        r: 20,
      },
      {
        id: 'croquet-hoop-3',
        action: 'hoop',
        order: 3,
        requiresBumper: 'flamingo-3',
        orientation: 'vertical',
        direction: 1,
        aperture: 17,
        x: 292,
        y: 136,
        r: 20,
      },
    ],
    bumpers: [
      {
        id: 'flamingo-1',
        targetHoopId: 'croquet-hoop-1',
        x: 86,
        y: 548,
        r: 18,
        impulseX: 5.4,
        impulseY: -0.74,
        flightDuration: 1800,
        artSize: 58,
      },
      {
        id: 'flamingo-2',
        targetHoopId: 'croquet-hoop-2',
        requiresSwitches: ['croquet-hoop-1'],
        x: 286,
        y: 354,
        r: 18,
        impulseX: -5.4,
        impulseY: -0.7,
        flightDuration: 1800,
        artSize: 58,
      },
      {
        id: 'flamingo-3',
        targetHoopId: 'croquet-hoop-3',
        requiresSwitches: ['croquet-hoop-2'],
        x: 72,
        y: 164,
        r: 18,
        impulseX: 5.4,
        impulseY: -0.7,
        flightDuration: 1800,
        artSize: 58,
      },
    ],
    gates: [
      { id: 'croquet-lane-1', switchId: 'croquet-hoop-1', x: 242, y: 486, w: 100, h: 18 },
      { id: 'croquet-lane-2', switchId: 'croquet-hoop-2', x: 242, y: 294, w: 100, h: 18 },
      { id: 'croquet-lane-3', switchId: 'croquet-hoop-3', x: 242, y: 102, w: 100, h: 18 },
    ],
    movers: [
      { id: 'croquet-card-1', type: 'card', x: 120, y: 434, w: 48, h: 15, axis: 'x', range: 150, speed: 0.0018 },
      { id: 'croquet-card-2', type: 'card', x: 224, y: 244, w: 48, h: 15, axis: 'x', range: -150, speed: 0.0022, phase: 1.2 },
    ],
    walls: [
      ...border,
      { x: 18, y: 486, w: 224, h: 18 },
      { x: 112, y: 390, w: 230, h: 18 },
      { x: 18, y: 294, w: 224, h: 18 },
      { x: 112, y: 198, w: 230, h: 18 },
      { x: 18, y: 102, w: 224, h: 18 },
    ],
  },
  {
    id: 'trial-of-names',
    order: 8,
    chapter: '终章',
    eyebrow: 'VIII · 名字审判',
    name: '谁偷走了她的名字',
    mechanic: '全部机制综合',
    parTime: 120000,
    hint: '找回三个词，旋转法庭，再点亮证词印章',
    quote: '当所有人都要求她证明自己，她终于决定亲口说出答案。',
    story: [
      {
        speaker: '红心国王',
        portrait: 'queen',
        text: '审判失窃的馅饼！先宣读最重要的证据：凡是不合适的证据，都不算证据。',
      },
      {
        speaker: '红心女王',
        portrait: 'queen',
        text: '先砍头，再宣判！',
      },
      {
        speaker: '爱丽丝',
        portrait: 'alice',
        text: '你们不过是一副纸牌。我的名字不需要由这座法庭批准。',
      },
    ],
    eventStories: {
      'collect:name-3': {
        speaker: '爱丽丝',
        portrait: 'alice',
        text: '我。记得。自己。三个词已经足够让我站在这里。',
      },
      'collect:caterpillar-gift': {
        speaker: '毛毛虫的回声',
        portrait: 'caterpillar',
        text: '你保留了一小片蘑菇。变小不是退缩，而是看见另一条路。',
      },
      'collect:tea-watch-gift': {
        speaker: '帽匠的回声',
        portrait: 'hatter',
        text: '借你七秒钟。时间会停下，纸牌却不会知道自己已经迟到。',
      },
      'collect:mirror-ribbon': {
        speaker: '镜中的红后',
        portrait: 'queen',
        text: '这条缎带能替你挡住一次错误的方向。',
      },
      'collect:flamingo-feather': {
        speaker: '火烈鸟',
        portrait: 'flamingo',
        text: '把羽毛留着。下一张撞来的纸牌，会先撞上女王自己的规则。',
      },
    },
    start: { x: 180, y: 572 },
    goal: {
      x: 159,
      y: 36,
      w: 42,
      h: 56,
      requires: {
        fragments: 3,
        switches: ['verdict'],
        rotations: { 'court-room': 1 },
      },
    },
    fragments: ['我', '记得', '自己'],
    ending: true,
    inheritances: [
      {
        choiceAt: 'caterpillar-crossroad',
        choice: 'mushroom',
        items: [
          { id: 'caterpillar-gift', type: 'potion', x: 298, y: 568, r: 13 },
        ],
        sizeGates: [
          { id: 'mushroom-shortcut', x: 268, y: 344, w: 74, h: 18, maxRadius: 9 },
        ],
      },
      {
        choiceAt: 'caterpillar-crossroad',
        choice: 'tea',
        items: [
          { id: 'tea-watch-gift', type: 'timepiece', x: 298, y: 568, r: 13, duration: 7000 },
        ],
      },
      {
        choiceAt: 'queen-garden',
        choice: 'mirror',
        items: [
          { id: 'mirror-ribbon', type: 'shield', x: 58, y: 488, r: 13, color: '#b9d9ef' },
        ],
      },
      {
        choiceAt: 'queen-garden',
        choice: 'croquet',
        items: [
          { id: 'flamingo-feather', type: 'shield', x: 58, y: 488, r: 13, color: '#eda6ba' },
        ],
      },
    ],
    items: [
      { id: 'name-1', type: 'fragment', word: '我', x: 54, y: 468, r: 13 },
      { id: 'name-2', type: 'fragment', word: '记得', x: 300, y: 350, r: 13 },
      { id: 'name-3', type: 'fragment', word: '自己', x: 58, y: 206, r: 13 },
      { id: 'trial-checkpoint', type: 'checkpoint', x: 300, y: 398, r: 12 },
      { id: 'cameo-trial', type: 'curiosity', x: 300, y: 294, r: 11 },
    ],
    switches: [
      { id: 'verdict', x: 300, y: 170, r: 18 },
      {
        id: 'court-crank',
        action: 'rotate',
        target: 'court-room',
        symbol: '↻',
        x: 58,
        y: 300,
        r: 18,
      },
    ],
    rotators: [
      {
        id: 'court-room',
        centerX: 180,
        centerY: 300,
        states: 2,
        walls: [{ x: 180, y: 293, w: 80, h: 14 }],
      },
    ],
    zones: [{ type: 'mirror', x: 100, y: 252, w: 160, h: 120 }],
    hazards: [
      { id: 'ink-1', type: 'whirlpool', x: 180, y: 470, r: 17 },
      { id: 'ink-2', type: 'whirlpool', x: 180, y: 170, r: 17 },
    ],
    movers: [
      { id: 'jury-1', type: 'card', x: 40, y: 402, w: 48, h: 15, axis: 'x', range: 230, speed: 0.0018 },
      { id: 'jury-2', type: 'card', x: 270, y: 222, w: 48, h: 15, axis: 'x', range: -230, speed: 0.0021, phase: 1.6 },
      {
        id: 'court-clock',
        type: 'watch',
        path: 'orbit',
        centerX: 180,
        centerY: 170,
        radiusX: 94,
        radiusY: 38,
        w: 27,
        h: 27,
        speed: 0.0018,
        phase: 0.7,
      },
    ],
    walls: [
      ...border,
      { x: 18, y: 526, w: 116, h: 18 },
      { x: 226, y: 526, w: 116, h: 18 },
      { x: 92, y: 438, w: 250, h: 18 },
      { x: 18, y: 344, w: 250, h: 18 },
      { x: 92, y: 250, w: 250, h: 18 },
      { x: 18, y: 156, w: 250, h: 18 },
      { x: 92, y: 92, w: 250, h: 18 },
    ],
  },
];

export const levels = levelList;
export const levelById = Object.fromEntries(levelList.map((level) => [level.id, level]));
export const firstLevelId = levelList[0].id;

export function getLevel(levelId) {
  return levelById[levelId] || levelList[0];
}

export function getPlayableLevel(levelId, choices = {}) {
  const level = getLevel(levelId);
  if (!level.inheritances?.length) return level;
  const inherited = level.inheritances.filter(
    (entry) => choices[entry.choiceAt] === entry.choice,
  );
  if (!inherited.length) return level;
  return {
    ...level,
    items: [
      ...(level.items || []),
      ...inherited.flatMap((entry) => entry.items || []),
    ],
    sizeGates: inherited.flatMap((entry) => entry.sizeGates || []),
  };
}
